### ISSUE TITLE
ExtJS version 7.0.0 GPL is available as NPM module

### ISSUE THREAD

**Issue by mmsmdali** [abenhamdine/awesome-extjs#46]
Sign up for [ExtJS version 7.0.0 GPL](https://sencha.myget.org) (Sencha ExtGen v7.0.0 GPL Edition - The Ext JS code generator). Only NPM access is available through login. No direct link available for download.

**Comment by mmsmdali** [comment]
Sign up for ExtJS version 7.0.0 GPL
[GPL Direct (Zip) download](https://www.sencha.com/legal/GPL)
[NPM Access](https://sencha.myget.org) (Sencha ExtGen v7.0.0 GPL Edition - The Ext JS code generator).

**Comment by abenhamdine** [comment]
thx ! I will edit the links
