### ISSUE TITLE
add https://www.leeboonstra.com/ ?

### ISSUE THREAD

**Issue by abenhamdine** [abenhamdine/awesome-extjs#5]
Lee no more works at sencha inc, but there's a bunch of good articles about the framework on her blog.

**Comment by scebotari66** [comment]
Agree! It has been an inspiration for me on many occasions.

**Comment by scebotari66** [comment]
I'm quite new to github collaboration so I wanted to ask what is the purpose of these issues that you have opened recently. You open them as a reminder for your self, or in order for people to vote for them, or to encourage others to submit PR requests? Or maybe all of the above :blush:

**Comment by abenhamdine** [comment]
> Or maybe all of the above

Exactly 😄 
I wanted also to encourage people to provide some feedbacks or suggest other blog entries.

Feel free to submit a PR on one or several of these issues, I would be glad to merge it, after a few days to allow people to comment if need be.

**Comment by scebotari66** [comment]
Great! Thanks for clarifying.
I will follow your example and open issues before adding a new resource :+1:
